name: Build API docs from Guix docstrings (PDF)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  api-docs:
    runs-on: ubuntu-22.04   # more predictable Guile packaging

    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (Guile 3.0, Pandoc, LaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git ca-certificates \
            guile-3.0 \
            pandoc \
            texlive-latex-base texlive-latex-recommended \
            texlive-fonts-recommended texlive-latex-extra
          # Show which guile we have
          which guile || true
          guile --version || true
          which guile-3.0
          guile-3.0 --version

      - name: Clone Guix sources (for module load path)
        run: |
          git clone --depth=1 https://git.savannah.gnu.org/git/guix.git
          ls -la guix | head -n 50

      - name: Extract docstrings to Markdown (force Guile 3.0)
        env:
          GUILE_LOAD_PATH: ${{ github.workspace }}/guix
        run: |
          guile-3.0 -c '(display %load-path)(newline)'
          guile-3.0 scripts/extract-docs.scm
          test -f build/guix-modules.md && head -n 20 build/guix-modules.md || true

      - name: Convert Markdown to PDF via pandoc
        run: |
          pandoc build/guix-modules.md \
            -V geometry:margin=1in \
            -V documentclass:article \
            -o build/guix-api-docs.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: guix-api-docs
          path: build/guix-api-docs.pdf
