name: Build Guix API docs with Guile Documentá (PDF)

on:
  workflow_dispatch:

jobs:
  documenta:
    runs-on: ubuntu-22.04

    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PREFIX: ${{ github.workspace }}/.local

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git ca-certificates \
            guile-3.0 \
            autoconf automake libtool make pkg-config \
            texinfo \
            texlive-latex-base texlive-latex-recommended \
            texlive-fonts-recommended texlive-latex-extra

      - name: Clone and build Guile Documentá
        run: |
          git clone --depth=1 https://gitlab.com/luis-felipe/guile-documenta.git
          cd guile-documenta
          # If the release already ships 'configure', you can skip autoreconf
          autoreconf -vfi || true
          ./configure --prefix="$PREFIX"
          make -j$(nproc)
          make install
          echo "$PREFIX/bin" >> $GITHUB_PATH
          documenta --help || true

      - name: Clone Guix sources
        run: |
          git clone --depth=1 https://git.savannah.gnu.org/git/guix.git
          ls guix | head -n 20

      - name: Generate Texinfo API with Documentá
        working-directory: guix
        run: |
          mkdir -p doc
          # Generate API texi into doc/api from the 'guix' module directory
          documenta api guix --destination doc/api
          # Create a tiny main.texi that includes the generated API
          cat > doc/main.texi <<'EOF'
          \input texinfo
          @setfilename guix-api
          @settitle Guix API (generated by Guile Documentá)
          @documentlanguage en
          @documentencoding UTF-8

          @node Top
          @top Guix API

          The following API reference was generated from Guix source files
          using Guile Documentá.

          @menu
          * API::
          @end menu

          @node API
          @chapter API
          @include api/index.texi

          @bye
          EOF

      - name: Build PDF from Texinfo (makeinfo/texi2pdf)
        working-directory: guix/doc
        run: |
          makeinfo --no-split --pdf -o guix-api-documenta.pdf main.texi
          ls -lh guix-api-documenta.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: guix-api-documenta
          path: guix/doc/guix-api-documenta.pdf
