name: Document치 from Codeberg (build Guix API PDF)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PREFIX: ${{ github.workspace }}/.local

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (Guile, build tools, Texinfo/LaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git autoconf automake libtool make pkg-config \
            guile-3.0 guile-3.0-dev \
            texinfo \
            texlive-latex-base texlive-latex-recommended \
            texlive-fonts-recommended texlive-latex-extra

      - name: Clone and build Guile Document치 (Codeberg)
        run: |
          set -eux
          git clone --depth=1 https://codeberg.org/luis-felipe/guile-documenta.git
          cd guile-documenta
          autoreconf -vfi || true
          ./configure --prefix="$PREFIX"
          make -j"$(nproc)"
          make install
          echo "$PREFIX/bin" >> "$GITHUB_PATH"
          documenta --version || true

      - name: Clone Guix sources
        run: |
          git clone --depth=1 https://git.savannah.gnu.org/git/guix.git

      - name: Generate Texinfo with Document치
        working-directory: guix
        run: |
          mkdir -p doc
          documenta api guix --destination doc/api
          cat > doc/main.texi <<'EOF'
          \input texinfo
          @setfilename guix-api
          @settitle Guix API (generated by Guile Document치)
          @documentlanguage en
          @documentencoding UTF-8
          @node Top
          @top Guix API
          @menu
          * API::
          @end menu
          @node API
          @chapter API
          @include api/index.texi
          @bye
          EOF

      - name: Build PDF
        working-directory: guix/doc
        run: |
          makeinfo --no-split --pdf -o guix-api-documenta.pdf main.texi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: guix-api-documenta
          path: guix/doc/guix-api-documenta.pdf
